package com.example.stocks.models.remote

import com.google.gson.annotations.SerializedName

data class CompanyProfile(
    @SerializedName("symbol") val symbol : String? = null,
    @SerializedName("price") val price : String? = null,
    @SerializedName("beta") val beta : Double? = null,
    @SerializedName("volAvg") val volAvg : String? = null,
    @SerializedName("mktCap") val mktCap : String? = null,
    @SerializedName("lastDiv") val lastDiv : String? = null,
    @SerializedName("range") val range : String? = null,
    @SerializedName("changes") val changes : String? = null,
    @SerializedName("companyName") val companyName : String? = null,
    @SerializedName("currency") val currency : String? = null,
    @SerializedName("cik") val cik : String? = null,
    @SerializedName("isin") val isin : String? = null,
    @SerializedName("cusip") val cusip : String? = null,
    @SerializedName("exchange") val exchange : String? = null,
    @SerializedName("exchangeShortName") val exchangeShortName : String? = null,
    @SerializedName("industry") val industry : String? = null,
    @SerializedName("website") val website : String? = null,
    @SerializedName("description") val description : String? = null,
    @SerializedName("ceo") val ceo : String? = null,
    @SerializedName("sector") val sector : String? = null,
    @SerializedName("country") val country : String? = null,
    @SerializedName("fullTimeEmployees") val fullTimeEmployees : String? = null,
    @SerializedName("phone") val phone : String? = null,
    @SerializedName("address") val address : String? = null,
    @SerializedName("city") val city : String? = null,
    @SerializedName("state") val state : String? = null,
    @SerializedName("zip") val zip : String? = null,
    @SerializedName("dcfDiff") val dcfDiff : String? = null,
    @SerializedName("dcf") val dcf : String? = null,
    @SerializedName("image") val image : String? = null,
    @SerializedName("ipoDate") val ipoDate : String? = null,
    @SerializedName("defaultImage") val defaultImage : Boolean? = null,
    @SerializedName("isEtf") val isEtf : Boolean? = null,
    @SerializedName("isActivelyTrading") val isActivelyTrading : Boolean? = null,
    @SerializedName("isAdr") val isAdr : Boolean? = null,
    @SerializedName("isFund") val isFund : Boolean? = null
)
